name: Build & Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Run Unit tests
        run: npm run test:ci

      - name: Run Playwright e2e tests
        run: npx playwright install --with-deps && npx playwright test

      - name: Build
        run: npm run build

      - name: Deploy to Github pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run ng -- deploy --repo="https://github.com/lesznyakmatyas/flexinform.git" --base-href=/flexinform/ --name=lesznyakmatyas --email=lesznyak.matyas@gmail.com
